### Wei Alexander Xin - wax1
###
### Top-level Makefile for COMS E6998 HW3
### Delegates to each part's Makefile
###

all:
	$(MAKE) -C Part-A
	$(MAKE) -C Part-B
	$(MAKE) -C Part-C

clean:
	$(MAKE) -C Part-A clean
	$(MAKE) -C Part-B clean
	$(MAKE) -C Part-C clean
